version: '3.8'

services:
  piping-extractor:
    build: .
    container_name: piping-line-extractor
    ports:
      - "8000:8000"
    environment:
      # Google Cloud Document AI Configuration
      - GOOGLE_CLOUD_PROJECT_ID=${GOOGLE_CLOUD_PROJECT_ID}
      - DOCUMENT_AI_PROCESSOR_ID=${DOCUMENT_AI_PROCESSOR_ID}
      - GOOGLE_APPLICATION_CREDENTIALS_JSON=${GOOGLE_APPLICATION_CREDENTIALS_JSON}
      # Optional: Override default location
      - DOCUMENT_AI_LOCATION=${DOCUMENT_AI_LOCATION:-us}
    volumes:
      # Mount a volume for temporary file storage (optional)
      - ./temp:/app/temp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - piping-network

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: piping-extractor-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - piping-extractor
    restart: unless-stopped
    networks:
      - piping-network
    profiles:
      - production

networks:
  piping-network:
    driver: bridge

volumes:
  temp-storage:
    driver: local 